brew "zsh"
brew "wget"
brew "htop"
brew "gpg" 
brew "gawk"
brew "tree"

tap "homebrew/cask-fonts"
brew "font-hack-nerd-font"

cask "iterm2" 
cask "flycut" 
cask "bartender"
cask "rectangle"
cask "lunar"
cask "1password"
cask "spotify"
cask "onedrive"
cask "vlc"
cask "signal"
cask "telegram"
cask "whatsapp"
cask "docker"
cask "visual-studio-code"
cask "android-studio"
cask "fork"
cask "openinterminal"
cask "obsidian"
cask "alfred"
cask "chromium"
cask "arc"
cask "poe"
cask "anydesk"
cask "stats"
cask "protonvpn"
cask "postman"

brew "awscli"
cask "google-cloud-sdk" # need to run post-install-google-cloud-sdk.sh
brew "asdf" # need to run post-install-asdf.sh
cask "miniconda" # need to run post-install-miniconda.sh

brew "ollama"
cask "logi-options-plus"
